name: Perf Test

on:
  pull_request:

# Cancel an in-progress run if a new run is started for the same PR or commit.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # required for google-github-actions/auth

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/620518129011/locations/global/workloadIdentityPools/bilt-rewards-prod/providers/github-provider
          service_account: github-actions@bilt-cicd.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Build
        run: |
          ./gradlew build

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input:
          - maven-100-artifacts/central
          - maven-100-artifacts/virtual
          - maven-100-artifacts/remote

    steps:      
      - name: Run Perf Test
        run: |
          RUN_DIR=/tmp/test/${{ matrix.input }} TEST=${{ matrix.input }} ./test/run.sh
